### ISSUE TITLE
Fetching seems to be completely broken

### ISSUE THREAD

**Issue by CyanLeader** [Kramoule/happypanda#11]
Seems like some development is still ongoing but I'm opening this anyway. I hope it will eventually get updated.

**Comment by Kramoule** [comment]
(Sorry for the late answer, I had no more notification on this repository)

Hello,

I did stop working on the project for a long time and I'm sorry for the people who wanted a new update (I'm still glad to know that there are people that still use this fork).
I only started recently to work again on it, mainly to update the python version (to use new dependencies update), which brought its share of incompatibilities. 
A new version is planned to be release after this (I should be able to finish it this month)

Concerning the fetching part, I didn't find any problem on my end with the v1.2. What problems do you have ?

**Comment by CyanLeader** [comment]
That's great to hear, I'm happy that this fork is still being supported.

I'm getting a critical error when trying to fetch metadata. To be fair I haven't tried fetching in ages and I only recently wanted to start organizing things (I've been waiting for an update that would add a "Circle" field) so I don't know if this is something that started happening recently or not. I'm quite sure it's not a problem with my installation since I used it before to fetch data on a ton of entries. 

Here is the log:

07-08 00:53 INFO   pewnet Initiating hash search on ehentai
07-08 00:53 INFO   pewnet Updating cookies...
07-08 00:53 CRITICAL app      File "E:\Repo\happypanda\version\fetch.py", line 528, in auto_web_metadata
  File "E:\Repo\happypanda\version\fetch.py", line 397, in _auto_metadata_process
  File "E:\Repo\happypanda\version\pewnet.py", line 1525, in search
  File "E:\Repo\happypanda\version\pewnet.py", line 1483, in search
  File "E:\Repo\happypanda\version\pewnet.py", line 1420, in no_hits_found_check

07-08 00:53 CRITICAL app    <class 'AttributeError'>: 'NoneType' object has no attribute 'find_all'

**Comment by Kramoule** [comment]
Are you using a login ? If that's the case, you may have to login again in Settings -> Web -> Logins (get your id/hash again in a web browser)
You can also try to set your default EH as e-hen in the Web -> Metadata settings if it's not already the case. (You can read your settings.ini file and check if the line `default ehen url = https://e-hentai.org/` is there to be sure)


Regarding the Circle field, I'm working on it.

**Comment by CyanLeader** [comment]
Thanks, re-applying the hash fixed the hard crash, I thought it'd have no effect since the software was telling me I was logged.

Best of luck with dev and thanks for maintaining this fork.
