### ISSUE TITLE
This branch isn't using the most updated version of HappyPanda.

### ISSUE THREAD

**Issue by CyanLeader** [Kramoule/happypanda#3]
HappyPanda 1.1 has issues when importing/exporting databases. The 1.2 version has been distributed before which fixes those issues (it's not on GitHub), but it's now missing the fixes introduced by this branch.

Would it be possible to combine the two? 1.2 can be found here: https://mega.nz/#!OMw3SIxb!uPYQu1xdNcD3X5t1tjWrX2F1edIwKsUQwgbhpT5nVp4

**Comment by Kramoule** [comment]
I see a lot of differences in the code, so it may take a while to see what to merge.
Can you tell me what the problem was  in a more specific way ? It could help me find the fix in that haystack.

**Comment by CyanLeader** [comment]
Hard for me to tell, but basically I requested the creator privately to update it due to errors I had when exporting libraries and importing them. IIRC it crashed while doing it and/or failed to process every library, If you want to investigate I'd suggest using an example library and then try exporting/importing it. My library was huge though (over 3k entries) so that might have been a factor.

Unrelated but would it be possible to add another descriptive field in this branch? I could really use a "circles" field, it was also added in HappyPandaX IIRC.

Edit. I'll also add that the creator had to update it several times in order to have it working so I don't think it's a simple fix.

**Comment by Kramoule** [comment]
I think I got that. Download this build and test out the Import/Export options.
[Happypanda-1.2-beta.zip](https://github.com/Kramoule/happypanda/files/3505606/Happypanda-1.2-beta.zip)

Regarding the circle field, I would have to fiddle with the database to add it and it's not something I'm ready to touch yet. When I have some time maybe I'll experiment some things, but I can't assure you anything.
