### ISSUE TITLE
Crash on start up...

### ISSUE THREAD

**Issue by Arspatheia** [Kramoule/happypanda#4]
Every time I choose a different sorting option than "Author", that's it. This is not a problem introduced by this fork, but do you think it's possible to fix the issue so I can sort my galleries to w.e option by default?
EDIT: Running Win 10-64bits, I don't know if the problem to this OS. I already tried running the software as admin but the error persists, every time I launch the program it tells me there's an critical error.

[happypanda.log](https://github.com/Kramoule/happypanda/files/3465058/happypanda.log)

**Comment by Kramoule** [comment]
I was able to reproduce the bug, I'll look into that.

**Comment by Kramoule** [comment]
@Arspatheia It should be fixed now but I'll make a new release when I'll fix another issue.

You should be able to fix the problem by deleting the following line in your *settings.ini*
```
current sort = artist
```
or by deleting the whole file.

**Comment by Arspatheia** [comment]
Oh, yes. I knew how to edit the .ini to not crash, but my point was to be able to use another sorting method by default instead of "title" and not crashing.
Looking forward that new version, tyvm.
