### ISSUE TITLE
CX_Freeze

### ISSUE THREAD

**Issue by Arspatheia** [Kramoule/happypanda#7]
So, the newest version still giving me this error when I try to lauch the program:
![F-Err](https://user-images.githubusercontent.com/48817867/64646444-bd144980-d3dc-11e9-90f3-0b1663373a49.png)

I checked another post where you address the issue and none of the solutions worked (move files, extract in a different location, run as admin, I even tried using different python versions).
Only one thing seems odd and it's that my main folder looks like this after extracting:
![Main-F](https://user-images.githubusercontent.com/48817867/64646634-1a0fff80-d3dd-11e9-8ea7-8dcc8822f093.png)
Much less cluttered than previous releases, am I missing something important here?

**Comment by Kramoule** [comment]
Thanks for the report.
It could be an error that happened on my side when I bundled the app. 
I'll work on that in a few days.

Some questions:
- What OS do you use ? Is it 64-bits ?
- Does the v1.1.1 works ?
    - If yes, can you try to copy the python35.dll from a v1.1.1 installation to a v1.2 folder and test it ? If it's still not working, try the same thing with the PyQt folder in lib/ (delete the lib/PyQt in v1.2 and copy the v1.1.1 PyQt instead)

**Comment by Arspatheia** [comment]
I'm using Windows 10 64-bits. Every other installment of Happypanda run just fine except v.1.2.
Using the .dll from v.1.1 didn't work, but replacing the "PyQt5" folder fixed the problem. Tyvm.
The .log shows nothing strange. The only thing I noticed was an update notification  when running the program for the first time.

**Comment by Kramoule** [comment]
Thanks for the feedback.

**Comment by Kramoule** [comment]
@Arspatheia 
The release file has been updated.
I did some more tests on my end, but if you can test it on your environment that would be great.

**Comment by Arspatheia** [comment]
This new iteration is now working correctly on my end and without any noticeable bug :D
Tyvm for the hard work, honestly.

P.S. I don't want to open a new issue just for this, so I'll drop another question here: Is/was happypanda supposed to work with cbz/cbr readers? because I'm trying to use CDisplay (the original, not the EX version) as my default Viewer but it only show the first page of every file.

**Comment by Kramoule** [comment]
You can change the *External Viewer Arguments* in the Advanced settings from **{$file}** to  **{$folder}** (so CDisplay loads the whole folder).

![Settings - Happypanda-2019-09-15 15_14_05](https://user-images.githubusercontent.com/22647002/64922109-a9495880-d7cb-11e9-928b-8fbf6194e1c4.png)

I personally had some trouble with CDisplay because it couldn't always open my galleries, and I found out that CDisplay Ex (https://www.cdisplayex.com/) was working much better.

**Comment by Arspatheia** [comment]
You are right, I tried to open some random file to test and only 1 out of 20 worked.
